module.exports.table = {
    Users: 'dbo.Users',
    UserRoles: 'dbo.UserRoles',
    RoleAccess: 'dbo.RoleAccess',
    RAResult: 'dbo.RAResult',
    RANCList: 'dbo.RANCList',
    RADetails: 'dbo.RADetails',
    RACA: 'dbo.RACA',
    LineResponsibility: 'dbo.LineResponsibility',
    LineRespChecklist: 'dbo.LineRespChecklist',
    Checklists: 'dbo.Checklists',
    AuditMC: 'dbo.AuditMC',
    AuditCE: 'dbo.AuditCE',
    AuditCategory: 'dbo.AuditCategory',
    EmailTemplate: 'dbo.EmailTemplate',
    UsersToken: 'dbo.UsersToken',
    NCStar: 'dbo.NCStar',
    Locations: 'dbo.Locations',
	AuditPlanning: 'dbo.AuditPlanning',
	AuditScheduled: 'dbo.AuditScheduled',
	Proxy : 'dbo.Proxy',
	RANCImage: 'dbo.RANCImage',
	RoleRequest: 'dbo.RoleRequest',
	Settings: 'dbo.Settings'
};